name: Docker Build and Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]  # Trigger on push to the main branch; change as needed
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
  packages: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest  # Replace with your image name
